[tool.black]
line-length = 88
target-version = ['py35', 'py36']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
    | \.rasa_core.log
    | \.story_graph.dot
  )/
)
'''
